config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'links#index'
  resources :links do # index new show edit update destroy
    member do
      put "like", to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
  end

end

app/models/link.rb
class Link < ActiveRecord::Base
  acts_as_votable
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :links
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]
  respond_to :html

  def index
    @links = Link.all
    respond_with(@links)
  end

  def show
    respond_with(@link)
  end

  def new
    @link = current_user.links.build
    respond_with(@link)
  end

  def edit
  end

  def create
    @link = current_user.links.build(link_params)
    @link.save
    respond_with(@link)
  end

  def update
    @link.update(link_params)
    respond_with(@link)
  end

  def destroy
    @link.destroy
    flash[:notice] = "You deleted a link!"
    respond_with(@link)
  end
  
  def upvote
    @link = set_link
    @link.upvote_by current_user
    redirect_to :back
  end
  
  def downvote
    @link = set_link
    @link.downvote_by current_user
    redirect_to :back
  end
  private
    def set_link
      @link = Link.find(params[:id])
    end

    def link_params
      params.require(:link).permit(:title, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BasicRedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do | name, msg | %>
    <%= content_tag( :div, msg, class: "flash", id: "#{name}" ) %>
  <% end %>
  
  <% if user_signed_in? %>
    <ul>
      <li><%= link_to 'Submit Link', new_link_path %></li>
      <li><%= link_to 'Account', edit_user_registration_path %></li>
      <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
    </ul>
  <% else %>
    <ul>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <li><%= link_to 'Sign In', new_user_session_path %></li>
    </ul>
  <% end %>
  <%= yield %>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form' %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<h1>Listing Links</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.title %></td>
        <td><%= link.url %></td>
          <td><%= link_to 'Show', link %></td>
          <% if link.user = current_user %>
            <td><%= link_to 'Edit', edit_link_path(link) %></td>
            <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path %>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form' %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @link.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @link.url %>
</p>
<div class="btn-group">
  <a class = "btn btn-default btn-sm" href = "<%= @link.url %>"></a>
  <%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
    <span class = "glyphicon glyphicon-chevron-up"></span>
    Upvote
    <% @link.get_upvotes.size %>
  <% end %>
  <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
    <span class = "glyphicon glyphicon-chevron-down"></span>
    Downvote
    <%= @link.get_downvotes.size %>
  <% end %>
</div>

<% if @link.user = current_user %>
  <%= link_to 'Edit', edit_link_path(@link) %> |
  <%= link_to 'Back', links_path %>
<% end %>